import { Schema, model, models } from "mongoose";

/**
 * An arena problem is a prompt-engineering challenge. It includes a
 * scenario, 2-4 test cases (user inputs + expected shape/content), and
 * a grading rubric. Generated by Groq on demand and cached indefinitely.
 */
const ArenaProblemSchema = new Schema(
  {
    problemId: { type: String, required: true, unique: true, index: true },
    slug: { type: String, required: true, index: true },
    title: { type: String, required: true },
    difficulty: {
      type: String,
      enum: ["beginner", "builder", "competitive"],
      required: true,
    },
    topic: { type: String, required: true }, // e.g. "extraction", "classification", "summarization"
    scenario: { type: String, required: true }, // The problem statement shown to the user.
    task: { type: String, required: true }, // One-line instruction.
    starterPrompt: { type: String, default: "" }, // Optional hint prompt to start with.
    testCases: {
      type: [
        {
          input: { type: String, required: true },
          expected: { type: String, required: true }, // What the output should contain / match.
          rubric: { type: String, required: true }, // How to judge this case.
        },
      ],
      required: true,
    },
    rubric: { type: String, required: true }, // Overall grading rubric for the grader LLM.
    maxScore: { type: Number, default: 100 },
    solvedCount: { type: Number, default: 0 },
    attemptCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

ArenaProblemSchema.index({ difficulty: 1, createdAt: -1 });

export const ArenaProblemModel =
  models.ArenaProblem || model("ArenaProblem", ArenaProblemSchema);
